version: "3.9"

services:
  web:
    build: .
    container_name: doctors_app
    ports:
      - "5000:5000"
    depends_on:
      - mongo
    environment:
      - FLASK_ENV=development

  mongo:
    image: mongo:7
    container_name: mongo_db
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
